verify the existing setup of google cloud project
Cloud-Prototyping-WS-2019-20/cp_ws_1920 pull request #107
Opened 2020-02-03 18:11 UTC by SantoshDhirwani

## Description
Added flag in the main script to get the user's input: 1 or 0
(0: use existing setup, 1: clean existing setup and a create a new one)

When the user selects 1: Clean the existing setup and create a new one

When the user selects 0: Check whether the number of nodes mentioned by the user in the config file is equal to the number of running VMs (in google cloud project9 or not.

## Related Issue
#91 

## Motivation and Context
It has been added to verify the existing configuration first and then use it.
Also, it is not a good idea to create a new setup without permission.

## How Has This Been Tested?
By executing the following in the bin folder:
python3 main.py 0 0
python3 main.py 0 0
python3 main.py 0 0
python3 main.py 0 0
python3 main.py 0 0

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-02-04 10:03 UTC, fayanpardo requested changes
I do not understand the execution. 
If I run main.py 2 0 without a SUT built I get the following output.
![image](https://user-images.githubusercontent.com/12150712/73733283-f65aa680-473b-11ea-97b8-1ce67556c292.png)

Successfully built? benchmark done and found minimum interval? there are no VMs running in GCP. An it just keeps running and failing but for the user seems that is working. Either the messages are not updated and clear or something else is failing.

If I run instead main.py 2 1. It builds and deletes and builds and deletes VMs constantly for every benchmark.
![image](https://user-images.githubusercontent.com/12150712/73734132-72a1b980-473d-11ea-9d07-a18db9a77710.png)

Either is not working or either is wasting a lot of time for something that was already working.

2020-02-04 10:03 UTC, fayanpardo commented on bin/sut/deploy-sut.sh
> -GCLOUD_OUTPUT=${5}
Why has this been deleted?

2020-02-04 12:07 UTC, SantoshDhirwani commented
@boxrhcp I think the previous approach was a bit complex. I added a simpler approach.

2020-02-08 11:20 UTC, ulalaa14 commented
i run a test with `python3 main.py 2 2` but it still running the command. even though it only handle parameter input 0 or 1 .
![image](https://user-images.githubusercontent.com/16094968/74084214-3dfb6e00-4a6d-11ea-8e07-f2bcecb0cf00.png)
![image](https://user-images.githubusercontent.com/16094968/74084220-57041f00-4a6d-11ea-9053-5bfa861c74a5.png)

2020-02-08 11:25 UTC, SantoshDhirwani commented
@ulalaa14  Nice catch. Added it.

2020-02-08 18:41 UTC, fayanpardo submitted a review, later dismissed
works! gj!

2020-02-09 10:46 UTC, SantoshDhirwani commented
@boxrhcp  There were some conflicts with the master in the ReadMe. I resolved them
 Could you please approve it again? Thanks.

2020-02-09 10:48 UTC, fayanpardo approved these changes

2020-02-09 10:50 UTC, merged