update bash-tag-build
Cloud-Prototyping-WS-2019-20/cp_ws_1920 pull request #5
Opened 2019-12-05 22:44 UTC by XhorxhinaT

building, tagging and pushing docker images into google container @boxrhcp

2019-12-07 14:35 UTC, eltalkarim requested changes

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +#$ docker  build /Users/[home]/cp_ws_1920/Docker/ether-node --tag ether-node
can you give a relative path to the docker? probably its ../Docker/ether-node

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +#$ docker  build /Users/[home]/cp_ws_1920/Docker/bootnode --tag bootnode
Same apply here

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +#$ docker  build /Users/[home]/cp_ws_1920/Docker/seale-rnode --tag sealer-node
same here

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +$ git clone https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920.git
this script will run within the repo so you don't need to clone it. please remove this line

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +$ docker  build /Users/[home]/cp_ws_1920/Docker/ether-node --tag ether-node
as discussed before please use relative path

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
>  #TODO write a script that will push all our docker images to GC so we can use them
please remove $ from all the script

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +$ gcloud auth configure-docker
can you explain how we are authenticating

2019-12-07 14:35 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +
test

2019-12-07 15:27 UTC, XhorxhinaT commented on bin/build-tag-push-docker-image.sh
> +#$ docker  build /Users/[home]/cp_ws_1920/Docker/ether-node --tag ether-node
done

2019-12-07 21:58 UTC, eltalkarim requested changes

2019-12-07 21:58 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +cd ~/cp_ws_1920/Docker
this is still an absolute path. please take a moment to understand what is the difference between a relative path and an absolute path

2019-12-07 21:58 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +
extra lines not needed

2019-12-07 21:58 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> +
extra lines not needed

2019-12-07 21:58 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> + gcloud auth configure-docker
i think you just need to authenticate one time

2019-12-07 21:58 UTC, eltalkarim commented on bin/build-tag-push-docker-image.sh
> + gcloud auth configure-docker
no need to reauthenticate you already did that at line 18

2019-12-08 10:42 UTC, eltalkarim requested changes
This script won't work because it is not handled going into the paths of the docker files. Please read more about relative paths.
For example you can just do cd ../../Docker/ether-node as I showed you yesterday

2019-12-10 18:22 UTC, XhorxhinaT reviewed
![image](https://user-images.githubusercontent.com/56897059/70556969-33624c80-1b82-11ea-9c6a-2e01845730f4.png)

2019-12-10 18:22 UTC, XhorxhinaT commented on bin/build-tag-push-docker-image.sh
> +cd ~/cp_ws_1920/Docker
I read about it here https://scriptingosx.com/2017/08/navigating-the-file-system/

2019-12-10 18:22 UTC, XhorxhinaT commented on bin/build-tag-push-docker-image.sh
> +cd ~/cp_ws_1920/Docker
the file cp_ws_1920/Docker is the file cloned from our GitHub file. Since relative paths have no root and no leading / is the path I wrote, therefore, not absolute, but relative and every User who clones out GitHub will have in their Pc the path cp_ws_1920/Docker downloaded...unless ofc they change the name of our GitHub file, which I highly doubt. So, please take a moment to understand the link i send you.

2019-12-10 20:02 UTC, eltalkarim approved these changes
Good job! @XhorxhinaT

2019-12-12 13:24 UTC, fayanpardo approved these changes

2019-12-12 15:03 UTC, merged