script receives info via arguments & create a new genesis file with s…
Cloud-Prototyping-WS-2019-20/cp_ws_1920 pull request #71
Opened 2020-01-18 18:32 UTC by ankushshr1993

Modification to previously created automated genesis creation script 

## Description
* The script receives details via arguments for a number of nodes, gas limit, and block interval
* Script creates a new genesis file with the same number of accounts as nodes and the specified gas limit and block interval.
 *genesis file and key stores are tested with geth. 
*Still needs to confirm if the nodes added in extra data are actually sealer nodes

## Related Issue
Automated genesis improvements #66

## Motivation and Context
variables can be added from console and nodes are added as a sealer.

## How Has This Been Tested?
Created and started a node on a network 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

<img width="1437" alt="Screenshot 2020-01-18 at 19 31 08" src="https://user-images.githubusercontent.com/38669738/72668630-3fff7d80-3a29-11ea-853b-83a10dde8d66.png">

2020-01-19 11:48 UTC, fayanpardo requested changes
I do not know if I'm executing it wrong but I try to run the code with "python create2.py init" it is asking user keyboard input for the variables instead of expecting arguments which is a requisite of the task. The user will not write any keyboard input in this SUT process, the SUT process will call this script and pass information via arguments. You are even parsing already "init" so I do not understand why adding extra complexity over something that was already being used.

Anyways I tried to test it and it is asking me for number of nodes and gaslimit which is correct but you forgot about block interval ( or maybe it goes after ?). And after giving my input I get the following error:
![image](https://user-images.githubusercontent.com/12150712/72680378-7684d900-3ab9-11ea-9801-4d9089dd8e79.png)

Also, to test the genesis file you are creating you can build 2 nodes and connect them manually or even connect them to a bootnode so they connect automatically.

And last thing, why did you created another script when the task was about improving the existing one? What is the config.json inside the dir doing? (i did not ask this in the previous PR because i did not see it tbh)

2020-01-20 17:58 UTC, ankushshr1993 commented
I think I am still unclear about passing it as an argument,that's why I asked you on slack regarding that too
<img width="563" alt="Screenshot 2020-01-20 at 18 57 18" src="https://user-images.githubusercontent.com/38669738/72748156-c09fb480-3bb6-11ea-9dd3-ae393de63df1.png">

As the error says please put the gas limit in hexadecimal(for eg. 0x00F42400) once you enter that it will ask you for block interval too

Yeah, you are right, I should have updated the same file, I will update it as a previous script with modification if you guys think it's working in this iteration. Config.json is taking a pre-defined password for ether nodes, I don't think it needs to be added as an argument.

2020-01-20 20:14 UTC, boxrhcp commented
Ah, I do not know why I understood from our tool context that with user input you meant writing the arguments when executing the script in the console. I thought it was pretty clear from our modularity design that scripts are going to send information through parsing arguments. Anyways it is an easy change, but again sorry for that.

About the hexadecimal value, now I got it. But can the script receive a decimal value and convert this into hexadecimal? The main script is not doing this because is sending the decimal values to every script.

What do you mean with "if it's working?"

Got ya about the config file, but the config file is already in another folder to organize the repository better. I actually saw that your branch is 11 commits behind master, you should pull the updates too see all the changes done until now. I anyways think that if you get this value from arguments you save LOC because the main script is already reading this value from the config file, and your script will be simpler.

2020-01-22 18:41 UTC, ankushshr1993 commented
Opened a new pull request

2020-01-22 18:41 UTC, closed without merging