add error handling in run-caliper.sh and run-caliper.py then retry
Cloud-Prototyping-WS-2019-20/cp_ws_1920 pull request #74
Opened 2020-01-20 09:41 UTC by ulalaa14

## Description

Add error handling in command script run-caliper.sh and run-caliper.py. If fail retry for several attempts.
Attempts value stored in config.json
Even fail, the next script still running well.
## Related Issue

https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/issues/60

## Motivation and Context

Build robustness in the current system by handling the error.

## How Has This Been Tested?

running python3 run-caliper.py
since in the main.py there is still error with the local environment

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-01-20 20:57 UTC, boxrhcp commented
So looking to your code I do not see anything wrong, but caliper is still returning 0 when failing to connect to the blockchain, thus caliper is not being executed again at all. Maybe we should go further, have you seen any possible way even if caliper command is actually benchmarking or not? We can maybe save the console output into a file and search for "benchmark successed" and then we know if it failed or not.

2020-01-20 21:12 UTC, ulalaa14 commented
hmmm. or probably we delete exit 0 in run-caliper.sh

2020-01-20 23:12 UTC, ulalaa14 commented
updated

2020-01-21 12:35 UTC, fayanpardo requested changes
Now when it fails it seems to retry as expected. However I tried the other way around, tested when caliper works and something seem to be wrong.
First of all it tries again even though it worked.
![image](https://user-images.githubusercontent.com/12150712/72805188-97ccfd00-3c52-11ea-94df-cc5f24873a70.png)

And after trying the number of times specified it says it fails.
![image](https://user-images.githubusercontent.com/12150712/72805095-605e5080-3c52-11ea-8982-d2e27a355b70.png)

I just saw your code has no exit(-1) in case of failure.

What I did to test was to execute main.py with your updates.

2020-01-23 11:14 UTC, ulalaa14 commented
updated it, however works in my local, i have trouble while hitting the node on cloud. need help to test it by others. hopefully it could work well. also i'm using exit 1 because the references i found stated exit 1 means exit because there is an error. nothing specify exit -1.

2020-01-24 11:30 UTC, boxrhcp commented
GJ! I tested it and now it does not repeat execution after success. However we may need to improve this script. 
![image](https://user-images.githubusercontent.com/12150712/73065653-6186bc00-3ea4-11ea-9b24-9c4350454ed5.png)
Here correctly works as expected.

![image](https://user-images.githubusercontent.com/12150712/73065749-9eeb4980-3ea4-11ea-996a-22820ecaf214.png)
Here caliper clearly fails with 1 gas limit but the command has run successfully so it is detected as correct.

We need to implement another way of detecting errors in caliper. What about this idea: Execute caliper command saving the printed output in a file ("caliper command > execution.log" for example) and then search in this file if contains "Benchmark run successful" which is printed when caliper benchmark finished successfully. If this line is not found then it is a failure and if it is found it is a success.

Any more ideas are welcome!

2020-01-24 12:32 UTC, ulalaa14 commented
updated it 👍

2020-01-24 18:05 UTC, boxrhcp commented on bin/run-caliper.py
> +            print("Meet maximum retry. Running caliper error.")
If this is the final caliper failure error I think it should directly after this message (and inside the if of course) exit(-1). If not main assumes everything ran correctly.

I just tested with all failures and even though caliper.sh returned the error, caliper.py returned success execution even after 3 retries.

2020-01-25 23:47 UTC, boxrhcp commented
It does not seem to get the message :/
![image](https://user-images.githubusercontent.com/12150712/73128812-5bdcc380-3fd5-11ea-9a79-51096b375879.png)

2020-01-26 14:17 UTC, ulalaa14 commented
updated by fixing typo and add wait command to make sure the first command finished

2020-01-26 17:52 UTC, fayanpardo approved these changes
GJ ! now works

2020-01-26 17:54 UTC, merged